export const mockTalents = [
  {
    _id: '1',
    name: 'John Doe',
    role: 'Actor',
    image: 'https://i.pravatar.cc/300?img=1',
    age: 28,
    price: 25,
    bio: 'Passionate actor with experience in theater and film.',
    hairColor: 'Brown',
    birthday: '1995-05-15',
    positiveKeywords: ['versatile', 'method acting', 'improv'],
    negativeKeywords: ['stunts', 'accents'],
    profileLink: 'https://example.com/johndoe',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=10',
      'https://i.pravatar.cc/300?img=20',
    ],
    isNew: true,
  },
  {
    _id: '2',
    name: 'Emma Watson',
    role: 'Model',
    image: 'https://i.pravatar.cc/300?img=2',
    age: 25,
    price: 30,
    bio: 'Professional model with a passion for fashion and photography.',
    hairColor: 'Blonde',
    birthday: '1998-08-22',
    positiveKeywords: ['runway', 'editorial', 'commercial'],
    negativeKeywords: ['swimwear'],
    profileLink: 'https://example.com/emmawatson',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=11',
      'https://i.pravatar.cc/300?img=21',
    ],
    isNew: false,
  },
  {
    _id: '3',
    name: 'Michael Chen',
    role: 'Musician',
    image: 'https://i.pravatar.cc/300?img=3',
    age: 32,
    price: 40,
    bio: 'Versatile musician skilled in multiple instruments and genres.',
    hairColor: 'Black',
    birthday: '1991-03-10',
    positiveKeywords: ['guitar', 'piano', 'vocals'],
    negativeKeywords: ['classical'],
    profileLink: 'https://example.com/michaelchen',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=12',
      'https://i.pravatar.cc/300?img=22',
    ],
    isNew: false,
  },
  {
    _id: '4',
    name: 'Sophia Rodriguez',
    role: 'Dancer',
    image: 'https://i.pravatar.cc/300?img=4',
    age: 23,
    price: 35,
    bio: 'Talented dancer specializing in contemporary and ballet.',
    hairColor: 'Brown',
    birthday: '2000-11-05',
    positiveKeywords: ['contemporary', 'ballet', 'choreography'],
    negativeKeywords: ['hip-hop'],
    profileLink: 'https://example.com/sophiarodriguez',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=13',
      'https://i.pravatar.cc/300?img=23',
    ],
    isNew: true,
  },
  {
    _id: '5',
    name: 'David Kim',
    role: 'Photographer',
    image: 'https://i.pravatar.cc/300?img=5',
    age: 29,
    price: 50,
    bio: 'Award-winning photographer with a unique eye for composition.',
    hairColor: 'Black',
    birthday: '1994-07-18',
    positiveKeywords: ['landscape', 'portrait', 'event'],
    negativeKeywords: ['wedding'],
    profileLink: 'https://example.com/davidkim',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=14',
      'https://i.pravatar.cc/300?img=24',
    ],
    isNew: false,
  },
  {
    _id: '6',
    name: 'Olivia Taylor',
    role: 'Voice Actor',
    image: 'https://i.pravatar.cc/300?img=6',
    age: 27,
    price: 45,
    bio: 'Versatile voice actor with experience in animation and video games.',
    hairColor: 'Red',
    birthday: '1996-09-30',
    positiveKeywords: ['animation', 'video games', 'commercials'],
    negativeKeywords: ['audiobooks'],
    profileLink: 'https://example.com/oliviataylor',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=15',
      'https://i.pravatar.cc/300?img=25',
    ],
    isNew: true,
  },
  {
    _id: '7',
    name: 'Alexander Novak',
    role: 'Makeup Artist',
    image: 'https://i.pravatar.cc/300?img=7',
    age: 31,
    price: 55,
    bio: 'Creative makeup artist specializing in special effects and high fashion.',
    hairColor: 'Blonde',
    birthday: '1992-02-14',
    positiveKeywords: ['special effects', 'high fashion', 'bridal'],
    negativeKeywords: ['body painting'],
    profileLink: 'https://example.com/alexandernovak',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=16',
      'https://i.pravatar.cc/300?img=26',
    ],
    isNew: false,
  },
  {
    _id: '8',
    name: 'Isabella Martinez',
    role: 'Fashion Designer',
    image: 'https://i.pravatar.cc/300?img=8',
    age: 34,
    price: 60,
    bio: 'Innovative fashion designer with a focus on sustainable and ethical fashion.',
    hairColor: 'Brown',
    birthday: '1989-12-03',
    positiveKeywords: ['sustainable', 'ethical', 'avant-garde'],
    negativeKeywords: ['fast fashion'],
    profileLink: 'https://example.com/isabellamartinez',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=17',
      'https://i.pravatar.cc/300?img=27',
    ],
    isNew: false,
  },
  {
    _id: '9',
    name: "Liam O'Connor",
    role: 'Stunt Performer',
    image: 'https://i.pravatar.cc/300?img=9',
    age: 30,
    price: 70,
    bio: 'Experienced stunt performer with expertise in martial arts and parkour.',
    hairColor: 'Brown',
    birthday: '1993-06-20',
    positiveKeywords: ['martial arts', 'parkour', 'wire work'],
    negativeKeywords: ['underwater stunts'],
    profileLink: 'https://example.com/liamoconnor',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=18',
      'https://i.pravatar.cc/300?img=28',
    ],
    isNew: true,
  },
  {
    _id: '10',
    name: 'Zoe Patel',
    role: 'Costume Designer',
    image: 'https://i.pravatar.cc/300?img=19',
    age: 33,
    price: 65,
    bio: 'Talented costume designer with experience in theater, film, and television.',
    hairColor: 'Black',
    birthday: '1990-04-12',
    positiveKeywords: ['period costumes', 'fantasy', 'contemporary'],
    negativeKeywords: ['sportswear'],
    profileLink: 'https://example.com/zoepatel',
    additionalPhotos: [
      'https://i.pravatar.cc/300?img=29',
      'https://i.pravatar.cc/300?img=30',
    ],
    isNew: false,
  },
];

export const mockConversations = [
  {
    _id: '1',
    firstName: 'Jane',
    lastName: 'Smith',
    companyName: undefined,
    avatar: 'https://i.pravatar.cc/150?img=1',
    role: 'model',
  },
  {
    _id: '2',
    firstName: undefined,
    lastName: undefined,
    companyName: 'Model Agency Inc.',
    avatar: 'https://i.pravatar.cc/150?img=2',
    role: 'agency',
  },
  {
    _id: '3',
    firstName: 'Mike',
    lastName: 'Johnson',
    companyName: undefined,
    avatar: 'https://i.pravatar.cc/150?img=3',
    role: 'model',
  },
];

export const mockMessages = [
  {
    _id: '1',
    sender: '1',
    recipient: 'currentUser',
    content: "Hi there! I'm interested in your portfolio.",
    timestamp: '2023-05-01T10:00:00Z',
  },
  {
    _id: '2',
    sender: 'currentUser',
    recipient: '1',
    content: 'Hello! Thank you for your interest. What would you like to know?',
    timestamp: '2023-05-01T10:05:00Z',
  },
  {
    _id: '3',
    sender: '1',
    recipient: 'currentUser',
    content: "I was wondering if you're available for a photoshoot next week?",
    timestamp: '2023-05-01T10:10:00Z',
  },
  {
    _id: '4',
    sender: '2',
    recipient: 'currentUser',
    content: 'We have a new opportunity for you. Are you interested?',
    timestamp: '2023-05-02T09:00:00Z',
  },
  {
    _id: '5',
    sender: 'currentUser',
    recipient: '2',
    content: 'Absolutely! Can you provide more details about the opportunity?',
    timestamp: '2023-05-02T09:15:00Z',
  },
  {
    _id: '6',
    sender: '3',
    recipient: 'currentUser',
    content: "Hey! I saw your recent work. It's amazing!",
    timestamp: '2023-05-03T14:00:00Z',
  },
];